import { BottomSheet } from './BottomSheet'
import { useSettingsStore } from '../stores/settingsStore'
const fontSizes = [18, 20, 22, 24, 28, 32]; const speeds = [0.75, 1, 1.25, 1.5, 2]
export function ReaderSettings({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { fontSize, showPinyin, autoFollow, playbackRate, setFontSize, setShowPinyin, setAutoFollow, setPlaybackRate } = useSettingsStore()
  const fontIndex = Math.max(0, fontSizes.indexOf(fontSize))
  return <BottomSheet open={open} title="阅读设置" onClose={onClose}><div className="settings-list"><section className="setting-group"><h3>字号</h3><div className="font-size-control"><button aria-label="减小字号" onClick={() => setFontSize(fontSizes[Math.max(0, fontIndex - 1)])}>A−</button><output>{fontSize}</output><button aria-label="增大字号" onClick={() => setFontSize(fontSizes[Math.min(fontSizes.length - 1, fontIndex + 1)])}>A+</button></div></section><ToggleRow label="拼音" value={showPinyin} off="关闭" on="显示" onChange={setShowPinyin} /><ToggleRow label="跟随朗读" value={autoFollow} off="关闭" on="开启" onChange={setAutoFollow} /><section className="setting-group"><h3>播放速度</h3><div className="choice-row">{speeds.map((speed) => <button key={speed} className={playbackRate === speed ? 'chosen' : ''} onClick={() => setPlaybackRate(speed)}>{speed.toFixed(speed % 1 === 0 ? 1 : 2)}×</button>)}</div></section></div></BottomSheet>
}
function ToggleRow({ label, value, off, on, onChange }: { label: string; value: boolean; off: string; on: string; onChange: (value: boolean) => void }) { return <section className="setting-row"><h3>{label}</h3><div className="choice-row"><button className={!value ? 'chosen' : ''} onClick={() => onChange(false)}>{off}</button><button className={value ? 'chosen' : ''} onClick={() => onChange(true)}>{on}</button></div></section> }
